services:
  # Base de datos para microservicio
  process-db:
    image: postgres:15
    environment:
      POSTGRES_DB: spopa
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - process_data:/var/lib/postgresql/data
      - ./ss_process_ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spopa-network

  # Microservicio de procesos
  process-ms:
    build: ./ss_process_ms
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=process-db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - DB_NAME=spopa
    depends_on:
      - process-db
    networks:
      - spopa-network

  # API Gateway
  api-gateway:
    build: ./api-getaway
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
    depends_on:
      - process-ms
    networks:
      - spopa-network

  # Servicios simulados
  users-service:
    image: node:20-alpine
    command: sh -c "echo 'Users service running on port 4001' && sleep infinity"
    ports:
      - "4003:4001"
    networks:
      - spopa-network

  internships-service:
    image: node:20-alpine
    command: sh -c "echo 'Internships service running on port 4002' && sleep infinity"
    ports:
      - "4004:4002"
    networks:
      - spopa-network

networks:
  spopa-network:
    driver: bridge

volumes:
  process_data: