
services:
  admin_ms:
    build: ./ss_admin_ms
    expose:
      - "8000"
    environment:
      - MONGODB_URL=mongodb+srv://smottad:spopa123@cluster0.kjmjmxo.mongodb.net/job_offers_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - spopa-network
  api-gateway-1:
    build: ./api-getaway
    container_name: api-gateway-1
    expose:
      - "3010"
    depends_on:
      - admin_ms
    networks:
      - spopa-network

  api-gateway-2:
    build: ./api-getaway
    container_name: api-gateway-2
    expose:
      - "3010"
    depends_on:
      - admin_ms
    networks:
      - spopa-network

  api-gateway-3:
    build: ./api-getaway
    container_name: api-gateway-3
    expose:
      - "3010"
    depends_on:
      - admin_ms
    networks:
      - spopa-network

  reverse-proxy:
    build: ./NGINX
    container_name: reverse-proxy
    ports:
      - "8010:8010"
    depends_on:
      - api-gateway-1
      - api-gateway-2
      - api-gateway-3
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - spopa-network

networks:
  spopa-network:
    driver: bridge
