apiVersion: apps/v1
kind: Deployment
metadata:
  name: spopa-frontend
  namespace: spopa-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spopa-frontend
  template:
    metadata:
      labels:
        app: spopa-frontend
    spec:
      containers:
      - name: frontend
        image: spopa-25-frontend-process-ms:latest
        ports:
        - containerPort: 4000
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: spopa-frontend-service
  namespace: spopa-production
spec:
  selector:
    app: spopa-frontend
  ports:
  - port: 80
    targetPort: 4000
  type: LoadBalancer