services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spopa
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # ¡esta línea es la que importa!
    networks:
      - spopa-network  


  process_ms:
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - spopa-network   

volumes:
  pgdata:
networks:
  spopa-network:
    external: true 