version: '3.8'

services:
  admin_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - spopa-network  

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - admin_db
    volumes:
      - .:/app
    networks:
      - spopa-network  

volumes:
  mongo_data:

networks:
  spopa-network:
    external: true  
