version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb+srv://smottad:spopa123@cluster0.kjmjmxo.mongodb.net/job_offers_db?retryWrites=true&w=majority&appName=Cluster0
