events {}

http {
    upstream api_gateway_cluster {
        server api-gateway-1:3010;
        server api-gateway-2:3010;
        server api-gateway-3:3010;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_gateway_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
