services:
  app:
    build:
      context: .
    container_name: offers_ms
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8010:8010"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=offers_db
      - DB_USERNAME=root
      - DB_PASSWORD=1234

  db:
    image: mysql:8
    container_name: offers_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: offers_db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
