services:
  app:
    build:
      context: .
    container_name: offers_ms
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8010:8010"
    depends_on:
      - db
    command: bash -c "sleep 10 && php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8010"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=offers_db
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq  
      - RABBITMQ_PORT=5673
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - RABBITMQ_EXCHANGE=events
    networks:
      - microservices_network

  db:
    image: mysql:8
    container_name: offers_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: offers_db
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - microservices_network
    

volumes:
  dbdata:

networks:
  microservices_network:
    external: true