services:
  # API Gateway
  api-gateway:
    build: .
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - USERS_SERVICE_URL=http://users-service:4001
      - INTERNSHIPS_SERVICE_URL=http://internships-service:4002
    depends_on:
      - process-ms-1
      - process-ms-2
      - process-ms-3
      - process-db
    volumes:
      - ./routes:/app/routes
      - ./.env:/app/.env
    networks:
      - spopa-network

  # Microservicio de procesos - Instancia 1
  process-ms-1:
    build: ../ss_process_ms
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=process-db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - DB_NAME=spopa
      - INSTANCE_ID=1
    depends_on:
      - process-db
    networks:
      - spopa-network

  # Microservicio de procesos - Instancia 2
  process-ms-2:
    build: ../ss_process_ms
    ports:
      - "4001:4000"  # 👈 Puerto externo diferente
    environment:
      - DB_HOST=process-db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - DB_NAME=spopa
      - INSTANCE_ID=2
    depends_on:
      - process-db
    networks:
      - spopa-network

  # Microservicio de procesos - Instancia 3
  process-ms-3:
    build: ../ss_process_ms
    ports:
      - "4002:4000"  # 👈 Puerto externo diferente
    environment:
      - DB_HOST=process-db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - DB_NAME=spopa
      - INSTANCE_ID=3
    depends_on:
      - process-db
    networks:
      - spopa-network

  # Base de datos para procesos
  process-db:
    image: postgres:15
    environment:
      POSTGRES_DB: spopa
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5433:5432"
    volumes:
      - process_data:/var/lib/postgresql/data
      - ../ss_process_ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spopa-network

  # Servicios simulados (mantener por ahora)
  users-service:
    image: node:20-alpine
    command: sh -c "echo 'Users service running on port 4001' && sleep infinity"
    ports:
      - "4003:4001"  # 👈 Cambié puerto para evitar conflictos
    networks:
      - spopa-network

  internships-service:
    image: node:20-alpine
    command: sh -c "echo 'Internships service running on port 4002' && sleep infinity"
    ports:
      - "4004:4002"  # 👈 Cambié puerto para evitar conflictos
    networks:
      - spopa-network

networks:
  spopa-network:
    driver: bridge

volumes:
  process_data:
  gateway_data: