services:
  # API Gateway
  api-gateway:
    build: .
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - USERS_SERVICE_URL=http://users-service:4001
      - INTERNSHIPS_SERVICE_URL=http://internships-service:4002
    volumes:
      - ./routes:/app/routes
      - ./.env:/app/.env
    networks:
      - spopa-network

  # Servicios simulados
  users-service:
    image: node:20-alpine
    command: sh -c "echo 'Users service running on port 4001' && sleep infinity"
    ports:
      - "4003:4001"
    networks:
      - spopa-network

  internships-service:
    image: node:20-alpine
    command: sh -c "echo 'Internships service running on port 4002' && sleep infinity"
    ports:
      - "4004:4002"
    networks:
      - spopa-network

networks:
  spopa-network:
    driver: bridge

volumes:
  gateway_data: