services:
  # API Gateway
  api-gateway:
    build: .
    ports:
      - "3010:3010"
    environment:
      - PORT=3010
      - USERS_SERVICE_URL=http://users-service:4001
      - INTERNSHIPS_SERVICE_URL=http://internships-service:4002
    depends_on:
      - process-ms
      - process-db
    volumes:
      - ./routes:/app/routes
      - ./.env:/app/.env
    networks:
      - spopa-network

  # Microservicio de procesos REAL
  process-ms:
    build: ../ss_process_ms  # Ruta a tu microservicio
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=process-db
      - DB_USER=usuario
      - DB_PASS=contraseña
      - DB_NAME=spopa
    depends_on:
      - process-db
    networks:
      - spopa-network

  # Base de datos para procesos
  process-db:
    image: postgres:15
    environment:
      POSTGRES_DB: spopa
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5433:5432" 
    volumes:
      - process_data:/var/lib/postgresql/data
      - ../ss_process_ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spopa-network

  # Servicios simulados (mantener por ahora)
  users-service:
    image: node:20-alpine
    command: sh -c "echo 'Users service running on port 4001' && sleep infinity"
    ports:
      - "4001:4001"
    networks:
      - spopa-network

  internships-service:
    image: node:20-alpine
    command: sh -c "echo 'Internships service running on port 4002' && sleep infinity"
    ports:
      - "4002:4002"
    networks:
      - spopa-network

networks:
  spopa-network:
    driver: bridge

volumes:
  process_data:
  gateway_data: